# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sim < Formula
  desc "Straight-forward, fast, scalable API simulation."
  homepage "https://github.com/kitproj/sim"
  version "0.0.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kitproj/sim/releases/download/v0.0.10/sim_0.0.10_Darwin_x86_64.tar.gz"
      sha256 "2ed8a406fb2e104be7cee4ed7ffed45397e5c06388bbaf6050e311b98ef8866a"

      def install
        bin.install "sim"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kitproj/sim/releases/download/v0.0.10/sim_0.0.10_Darwin_arm64.tar.gz"
      sha256 "dc7b1288e81f3ba067cecb63b375fdd905247ffe0280d526a6bf9e0523118470"

      def install
        bin.install "sim"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kitproj/sim/releases/download/v0.0.10/sim_0.0.10_Linux_arm64.tar.gz"
      sha256 "7c1ce5acac7cb1e6906c70da3f372fb88ed4cf2f7c08c8fd6872f05936e1914f"

      def install
        bin.install "sim"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kitproj/sim/releases/download/v0.0.10/sim_0.0.10_Linux_x86_64.tar.gz"
      sha256 "dc129d8b7431f7f5ef1c71547f1de6670a0e6fde5cbda7993d08b2eb20226931"

      def install
        bin.install "sim"
      end
    end
  end
end
