# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sim < Formula
  desc "Straight-forward, fast, scalable API simulation."
  homepage "https://github.com/kitproj/sim"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kitproj/sim/releases/download/v0.0.3/sim_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "4877ba230d92e0cedccfa26c73930dbc17dc41a8844f390852ad5d95c3e7692b"

      def install
        bin.install "sim"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kitproj/sim/releases/download/v0.0.3/sim_0.0.3_Darwin_arm64.tar.gz"
      sha256 "ffdabd48af1749f22a644e08d23e31c4d25e9651c327351d6d31393019d2ef46"

      def install
        bin.install "sim"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kitproj/sim/releases/download/v0.0.3/sim_0.0.3_Linux_arm64.tar.gz"
      sha256 "66cc195e30e9db30c444a17acd7092d20c32557edac5ab066f8cd13968f23f7b"

      def install
        bin.install "sim"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kitproj/sim/releases/download/v0.0.3/sim_0.0.3_Linux_x86_64.tar.gz"
      sha256 "162606186665a6b0a80d1319bc8d571e237a21e3269edf2d51d280294db527de"

      def install
        bin.install "sim"
      end
    end
  end
end
