# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sim < Formula
  desc "Straight-forward, fast, scalable API simulation."
  homepage "https://github.com/kitproj/sim"
  version "0.0.16"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kitproj/sim/releases/download/v0.0.16/sim_0.0.16_Darwin_x86_64.tar.gz"
      sha256 "88db7372b5a7730646b97c4b43bdf221fab3697663968269e93ed14f12b84f5b"

      def install
        bin.install "sim"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kitproj/sim/releases/download/v0.0.16/sim_0.0.16_Darwin_arm64.tar.gz"
      sha256 "292df2a237234d77c0b93b3dcb1e4b164f824efc6d0151793d1f4fb88256a621"

      def install
        bin.install "sim"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kitproj/sim/releases/download/v0.0.16/sim_0.0.16_Linux_arm64.tar.gz"
      sha256 "f7e703857ecc62ae54c8a51bbd355257f630ec684324a7cad6471ac3ec01cfa6"

      def install
        bin.install "sim"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kitproj/sim/releases/download/v0.0.16/sim_0.0.16_Linux_x86_64.tar.gz"
      sha256 "79f3e9d9bc1b07d6f354c08e2fdf2564448219de816825e028563fe23b8d8177"

      def install
        bin.install "sim"
      end
    end
  end
end
